// Turns the files under web/ into a C++ source file, so the admin page ships
// inside the binary and the scratch image still holds nothing but that binary.
//
//     embed <out.cpp> <url>=<file> [<url>=<file> ...]
//
// Written in C++ and built by the same makefile rather than as a script,
// because a shell or python in the build path would be the project's first
// build dependency. Built with HOSTCXX, since when CXX is a cross compiler this
// has to run on the machine doing the building.

#include <stdio.h>
#include <string>
#include <vector>

struct Asset {
    std::string url;
    std::string file;
    std::string symbol;
};

static const char *contentType(const std::string &path){
    if(path.size() > 5 && path.compare(path.size() - 5, 5, ".html") == 0)
        return "text/html; charset=utf-8";
    if(path.size() > 3 && path.compare(path.size() - 3, 3, ".js") == 0)
        return "application/javascript; charset=utf-8";
    if(path.size() > 4 && path.compare(path.size() - 4, 4, ".css") == 0)
        return "text/css; charset=utf-8";
    return "application/octet-stream";
}

// A C identifier per asset, so the generated file compiles whatever the URLs are.
static std::string symbolFor(const std::string &url, size_t index){
    std::string out = "asset_";
    char number[32];
    snprintf(number, sizeof(number), "%u_", (unsigned)index);
    out += number;
    for(size_t i = 0; i < url.size(); i++){
        char c = url[i];
        out += ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')) ? c : '_';
    }
    return out;
}

int main(int argc, char **argv){

    if(argc < 3){
        fprintf(stderr,"usage: embed <out.cpp> <url>=<file> ...\n");
        return 2;
    }

    std::vector<Asset> assets;

    for(int i = 2; i < argc; i++){
        std::string argument = argv[i];
        size_t split = argument.find('=');
        if(split == std::string::npos){
            fprintf(stderr,"embed: expected <url>=<file>, got %s\n",argv[i]);
            return 2;
        }
        Asset asset;
        asset.url = argument.substr(0,split);
        asset.file = argument.substr(split + 1);
        asset.symbol = symbolFor(asset.url,assets.size());
        assets.push_back(asset);
    }

    FILE *out = fopen(argv[1],"w");
    if(out == NULL){
        fprintf(stderr,"embed: cannot write %s\n",argv[1]);
        return 1;
    }

    fprintf(out,"// Generated by tools/embed.cpp. Do not edit; run `make web`.\n\n");
    fprintf(out,"#include \"web_assets.h\"\n\n");

    for(size_t i = 0; i < assets.size(); i++){

        FILE *in = fopen(assets[i].file.c_str(),"rb");
        if(in == NULL){
            fprintf(stderr,"embed: cannot read %s\n",assets[i].file.c_str());
            fclose(out);
            return 1;
        }

        fprintf(out,"static const unsigned char %s[] = {",assets[i].symbol.c_str());

        size_t length = 0;
        int byte;
        while((byte = fgetc(in)) != EOF){
            if((length % 16) == 0) fprintf(out,"\n    ");
            fprintf(out,"0x%02x,",(unsigned)byte);
            length++;
        }
        fclose(in);

        fprintf(out,"\n};\n\n");
        fprintf(out,"// %s, %u bytes\n\n",assets[i].file.c_str(),(unsigned)length);

        assets[i].file = "";                     // reuse the field for the length
        char number[32];
        snprintf(number,sizeof(number),"%u",(unsigned)length);
        assets[i].file = number;
    }

    fprintf(out,"static const WEB_ASSET table[] = {\n");
    for(size_t i = 0; i < assets.size(); i++)
        fprintf(out,"    { \"%s\", %s, %s, \"%s\" },\n",
                assets[i].url.c_str(), assets[i].symbol.c_str(),
                assets[i].file.c_str(), contentType(argv[i + 2]));
    fprintf(out,"    { 0, 0, 0, 0 }\n};\n\n");

    fprintf(out,
        "const WEB_ASSET *webAsset(const std::string &url){\n"
        "    for(int i = 0; table[i].url != 0; i++)\n"
        "        if(url == table[i].url)\n"
        "            return &table[i];\n"
        "    return 0;\n"
        "}\n");

    fclose(out);
    return 0;
}
